# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bacteria.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/bacteria.proto\"\x11\n\x0f\x42\x61\x63teriaRequest\"\xb1\x01\n\x0c\x42\x61\x63teriaInfo\x12\x0e\n\x06volume\x18\x01 \x01(\x02\x12*\n\rcurrent_state\x18\x02 \x01(\x0e\x32\x13.BacteriaInfo.State\x12*\n\rcan_switch_to\x18\x03 \x03(\x0e\x32\x13.BacteriaInfo.State\"9\n\x05State\x12\n\n\x06STABLE\x10\x00\x12\x0b\n\x07GROWING\x10\x01\x12\r\n\tSHRINKING\x10\x02\x12\x08\n\x04\x44\x45\x41\x44\x10\x03\"<\n\x12\x43hangeStateRequest\x12&\n\tnew_state\x18\x01 \x01(\x0e\x32\x13.BacteriaInfo.State2p\n\x0f\x42\x61\x63teriaService\x12*\n\x07GetInfo\x12\x10.BacteriaRequest\x1a\r.BacteriaInfo\x12\x31\n\x0b\x43hangeState\x12\x13.ChangeStateRequest\x1a\r.BacteriaInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bacteria_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BACTERIAREQUEST']._serialized_start=24
  _globals['_BACTERIAREQUEST']._serialized_end=41
  _globals['_BACTERIAINFO']._serialized_start=44
  _globals['_BACTERIAINFO']._serialized_end=221
  _globals['_BACTERIAINFO_STATE']._serialized_start=164
  _globals['_BACTERIAINFO_STATE']._serialized_end=221
  _globals['_CHANGESTATEREQUEST']._serialized_start=223
  _globals['_CHANGESTATEREQUEST']._serialized_end=283
  _globals['_BACTERIASERVICE']._serialized_start=285
  _globals['_BACTERIASERVICE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
